name: Waka Readme

on:
  schedule:
    # Jalankan setiap 6 jam
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anmol098/waka-readme-stats@master
        with:
          # Perbaikan: diubah ke huruf kecil
          wakatime_api_key: ${{ secrets.WAKATIME_API_KEY }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          # Perbaikan: Menghapus parameter yang tidak valid (SHOW_TITLE, dll.)
